# Generated by Django 5.2.5 on 2025-09-26 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surplustracker',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='surplustracker',
            name='last_applied_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surplustracker',
            name='last_applied_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surplustracker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
